#!/usr/bin/env node

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const distRoot = resolve(projectRoot, 'dist');
const gasFiles = readdirSync(projectRoot).filter((name) => name.endsWith('.gs')).sort();
const htmlFiles = new Set(readdirSync(projectRoot).filter((name) => name.endsWith('.html')));
const claspIgnore = readFileSync(resolve(projectRoot, '.claspignore'), 'utf8');

if (!claspIgnore.split(/\r?\n/).includes('dist/**')) {
  throw new Error('Refusing to build: .claspignore must contain dist/** so clasp never pushes the combined files.');
}

const gasBanner = [
  '// Generated by `npm run build` for environments where clasp is unavailable.',
  '// Paste this entire file into Code.gs. Edit the split source files, not this file.',
  ''
].join('\n');
const combinedGas = gasBanner + gasFiles.map((fileName) => {
  const source = readFileSync(resolve(projectRoot, fileName), 'utf8').trimEnd();
  return `// ===== ${fileName} =====\n${source}\n`;
}).join('\n');

// Catch collisions or boundary problems that only appear after all GAS files are combined.
new vm.Script(combinedGas, { filename: 'dist/Code.gs' });

const includePattern = /<\?!=\s*include\(\s*(['"])([^'"]+)\1\s*\)\s*;?\s*\?>/g;

function expandHtml(fileName, parents = []) {
  const normalizedName = fileName.endsWith('.html') ? fileName : `${fileName}.html`;
  if (!htmlFiles.has(normalizedName)) {
    throw new Error(`HTML include not found: ${normalizedName}`);
  }
  if (parents.includes(normalizedName)) {
    throw new Error(`Circular HTML include: ${parents.concat(normalizedName).join(' -> ')}`);
  }

  const source = readFileSync(resolve(projectRoot, normalizedName), 'utf8');
  return source.replace(includePattern, (_match, _quote, includedName) => {
    if (!/^[A-Za-z0-9_-]+$/.test(includedName)) {
      throw new Error(`Unsupported HTML include name in ${normalizedName}: ${includedName}`);
    }
    const includedFile = `${includedName}.html`;
    const content = expandHtml(includedFile, parents.concat(normalizedName)).trimEnd();
    return `<!-- ===== BEGIN ${includedFile} ===== -->\n${content}\n<!-- ===== END ${includedFile} ===== -->`;
  });
}

const expandedIndex = expandHtml('Index.html').trimEnd() + '\n';
const htmlBanner = '<!-- Generated by `npm run build`. Paste this entire file into Index.html. -->\n';
const combinedHtml = /^<!doctype html>\s*\n/i.test(expandedIndex)
  ? expandedIndex.replace(/^<!doctype html>\s*\n/i, (doctype) => doctype + htmlBanner)
  : htmlBanner + expandedIndex;

for (const [index, match] of [...combinedHtml.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].entries()) {
  new vm.Script(match[1], { filename: `dist/Index.html:script-${index}` });
}

mkdirSync(distRoot, { recursive: true });
writeFileSync(resolve(distRoot, 'Code.gs'), combinedGas, 'utf8');
writeFileSync(resolve(distRoot, 'Index.html'), combinedHtml, 'utf8');

process.stdout.write(`Built dist/Code.gs from ${gasFiles.length} GAS files and dist/Index.html from ${htmlFiles.size} HTML files.\n`);
